relationships:
  - name: apmApplicationCallsAzureRedisEnterpriseCache
    version: "1"
    entitlements:
      matching: anyOf
      values:
        - auto_discovery_entities_ccu
        - auto_discovery_entities_ccu_discount_usage
        - azure_auto_discovery
        - azure_auto_discovery_discount_usage
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        regex: "^Datastore/instance/Redis/[a-z0-9\\-]+\\.[a-z0-9\\-]+\\.redisenterprise\\.cache\\.azure\\.net/[0-9]+$"
    relationship:
      expires: PT75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AZUREREDISENTERPRISECACHE
          fields:
            - field: endpoint
              attribute: metricName__4 
