relationships:
  - name: ApmApplicationISextEbpfService
    version: "1"
    origins:
      - Distributed Tracing
      - APM Metrics
    conditions:
      - attribute: eventType
        anyOf: ["Span", "Metric"]
      - attribute: entity.type
        present: false
    relationship:
      expires: P24H
      relationshipType: IS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: EXTEBPFSERVICE
          fields:
            - field: service.name
              attribute: entity.name