relationships:
  - name: apmProducesAwsMskTopic
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        regex: "^MessageBroker/Kafka/Nodes/[^/]*\\.amazonaws\\.com:9[0-9]+/Produce/.*"
    relationship:
      expires: P75M
      relationshipType: PRODUCES
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: KAFKATOPIC
          fields:
            - field: clusterName
              capture:
                attribute: metricName__4
                regex: "^[^\\.]+\\.([^\\.]+)\\.[^\\.]+\\.[^\\.]+\\.kafka\\.[^\\.]+\\.amazonaws\\.com:9[0-9]+"
            - field: region
              capture:
                attribute: metricName__4
                regex: "^[^\\.]+\\.[^\\.]+\\.[^\\.]+\\.[^\\.]+\\.kafka\\.([^\\.]+)\\.amazonaws\\.com:9[0-9]+"
            - field: topic
              attribute: metricName__6

  - name: apmConsumesAwsMskTopic
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        regex: "^MessageBroker/Kafka/Nodes/[^/]*\\.amazonaws\\.com:9[0-9]+/Consume/.*"
    relationship:
      expires: P75M
      relationshipType: CONSUMES
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: KAFKATOPIC
          fields:
            - field: clusterName
              capture:
                attribute: metricName__4
                regex: "^[^\\.]+\\.([^\\.]+)\\.[^\\.]+\\.[^\\.]+\\.kafka\\.[^\\.]+\\.amazonaws\\.com:9[0-9]+"
            - field: region
              capture:
                attribute: metricName__4
                regex: "^[^\\.]+\\.[^\\.]+\\.[^\\.]+\\.[^\\.]+\\.kafka\\.([^\\.]+)\\.amazonaws\\.com:9[0-9]+"
            - field: topic
              attribute: metricName__6

  - name: apmProducesConfluentCloudKafkaTopic
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        regex: "^MessageBroker/Kafka/Nodes/.*.confluent.cloud:9[0-9]+/Produce/.+"
    relationship:
      expires: P75M
      relationshipType: PRODUCES
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: KAFKATOPIC
          fields:
            - field: bootstrapServers
              attribute: metricName__4
            - field: topic
              attribute: metricName__6

  - name: apmConsumesConfluentCloudKafkaTopic
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        regex: "^MessageBroker/Kafka/Nodes/.*.confluent.cloud:9[0-9]+/Consume/.+"
    relationship:
      expires: P75M
      relationshipType: CONSUMES
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: KAFKATOPIC
          fields:
            - field: bootstrapServers
              attribute: metricName__4
            - field: topic
              attribute: metricName__6

  - name: apmProducesKafkaTopic
    version: "1"
    origins:
      - Infrastructure Agent
      - OnHost Integration
    conditions:
      - attribute: eventType
        anyOf: [ "KafkaProducerSample" ]
      - attribute: integrationName
        anyOf: [ "com.newrelic.kafka" ]
      - attribute: clusterName
        present: true
      - attribute: topic
        present: true
    relationship:
      expires: P75M
      relationshipType: PRODUCES
      source:
        extractGuid:
          attribute: entityGuid
      target:
        buildGuid:
          account:
            attribute: accountId
          domain:
            value: INFRA
          type:
            value: KAFKATOPIC
          identifier:
            fragments:
              - value: "ka-topic:"
              - attribute: topic
              - value: ":clustername="
              - attribute: clusterName
            hashAlgorithm: FARM_HASH

  - name: apmConsumesKafkaTopic
    version: "1"
    origins:
      - Infrastructure Agent
      - OnHost Integration
    conditions:
      - attribute: eventType
        anyOf: [ "KafkaConsumerSample" ]
      - attribute: integrationName
        anyOf: [ "com.newrelic.kafka" ]
      - attribute: clusterName
        present: true
      - attribute: topic
        present: true
    relationship:
      expires: P75M
      relationshipType: CONSUMES
      source:
        extractGuid:
          attribute: entityGuid
      target:
        buildGuid:
          account:
            attribute: accountId
          domain:
            value: INFRA
          type:
            value: KAFKATOPIC
          identifier:
            fragments:
              - value: "ka-topic:"
              - attribute: topic
              - value: ":clustername="
              - attribute: clusterName
            hashAlgorithm: FARM_HASH