relationships:
  - name: apmApplicationCallsInfraMSSQLInstance
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        # "datastore/instance/MSSQL/$host/$port"
        startsWith: "datastore/instance/MSSQL/"
    relationship:
      expires: PT75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        buildGuid:
          account:
            lookup: true
          domain:
            value: INFRA
          type:
            value: MSSQLINSTANCE
            valueInGuid: NA
          identifier:
            fragments:
              - value: "ms-instance:"
              - attribute: metricName__4 # hostname
              - value: ":instance="
              # This rule assumes that the instance name is equal to the db hostname in lower case.
              - attribute: metricName__4 # hostname in lowerCase
                operations:
                  - operation: toLowerCase
            hashAlgorithm: FARM_HASH

  - name: apmApplicationCallsInfraMSSQLInstanceTimeslice
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        regex: "^[Dd]atastore/instance/MSSQL/[^/]+/[0-9]+"
    relationship:
      expires: PT75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: MSSQLINSTANCE
          fields:
            - field: dbHostname
              attribute: metricName__4
            - field: serverPort
              attribute: metricName__5