relationships:
  - name: apmApplicationHostsOnAzureFunctionsApp
    version: "1"
    entitlements:
      matching: anyOf
      values:
        - auto_discovery_entities_ccu
        - auto_discovery_entities_ccu_discount_usage
        - azure_auto_discovery
        - azure_auto_discovery_discount_usage
    origins:
      - Azure Integration
    conditions:
      - attribute: eventType
        anyOf: [ "Metric" ]
      - attribute: entity.type
        anyOf: [ "AZUREFUNCTIONSAPP" ]
      - attribute: azure.resourceId
        present: true
    relationship:
      expires: PT75M
      relationshipType: HOSTS
      source:
        lookupGuid:
          candidateCategory: APMAPPLICATION
          fields:
            - field: resourceId
              attribute: azure.resourceId
      target:
        extractGuid:
          attribute: entity.guid
          entityType:
            value: AZUREFUNCTIONSAPP
  - name: apmApplicationHostsOnAzureWebApp
    version: "1"
    entitlements:
      matching: anyOf
      values:
        - auto_discovery_entities_ccu
        - auto_discovery_entities_ccu_discount_usage
        - azure_auto_discovery
        - azure_auto_discovery_discount_usage
    origins:
      - Azure Integration
    conditions:
      - attribute: eventType
        anyOf: [ "Metric" ]
      - attribute: entity.type
        anyOf: [ "AZUREWEBAPP" ]
      - attribute: azure.resourceId
        present: true
    relationship:
      expires: PT75M
      relationshipType: HOSTS
      source:
        lookupGuid:
          candidateCategory: APMAPPLICATION
          fields:
            - field: resourceId
              attribute: azure.resourceId
      target:
        extractGuid:
          attribute: entity.guid
          entityType:
            value: AZUREWEBAPP
  - name: apmApplicationHostsOnAzureAppServiceWebApp
    version: "1"
    entitlements:
      matching: anyOf
      values:
        - auto_discovery_entities_ccu
        - auto_discovery_entities_ccu_discount_usage
        - azure_auto_discovery
        - azure_auto_discovery_discount_usage
    origins:
      - Azure Integration
    conditions:
      - attribute: eventType
        anyOf: [ "AzureAppServiceWebAppSample" ]
      - attribute: nr.entityType
        anyOf: [ "AZUREAPPSERVICEWEBAPP" ]
      - attribute: resourceId
        present: true
    relationship:
      expires: PT75M
      relationshipType: HOSTS
      source:
        lookupGuid:
          candidateCategory: APMAPPLICATION
          fields:
            - field: resourceId
              attribute: resourceId
      target:
        extractGuid:
          attribute: entityGuid
          entityType:
            value: AZUREAPPSERVICEWEBAPP