relationships:
  - name: apmCallsOtelElasticsearchCluster
    version: "1"
    origins:
      - OpenTelemetry
    conditions:
      - attribute: eventType
        anyOf: [ "Metric" ]
      - attribute: instrumentation.provider
        anyOf: [ "opentelemetry" ]
      - attribute: entity.type
        anyOf: [ "SERVICE" ]
      - attribute: es.cluster.name
        present: true
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        buildGuid:
          account:
            attribute: accountId
          domain:
            value: INFRA
          type:
            value: ELASTICSEARCHCLUSTER
          identifier:
            fragments:
              - attribute: es.cluster.name
            hashAlgorithm: FARM_HASH