relationships:
  - name: k8sNamespaceContainsDeployment
    version: "1"
    origins:
      - Kubernetes Integration
    conditions: 
      - attribute: eventType
        anyOf: [ "K8sDeploymentSample" ]
    relationship:
      expires: PT75M
      relationshipType: CONTAINS
      source:
        lookupGuid:
          candidateCategory: KUBERNETES_NAMESPACE
          fields:
            - field: k8s.clusterName
              attribute: clusterName
            - field: k8s.namespaceName
              attribute: namespaceName
      target:
        extractGuid:
          attribute: entityGuid
          entityType:
            value: KUBERNETES_DEPLOYMENT  
  - name: otelKsmK8sNamespaceContainsDeployment
    # use kube-state-metrics kube_deployment_created
    version: "1"
    origins: 
      - OpenTelemetry
    conditions:
      - attribute: metricName
        anyOf: [ "kube_deployment_created" ]
    relationship:
      expires: PT75M
      relationshipType: CONTAINS
      source:
        buildGuid:
          account:
            lookup: true  
          domain:
            value: INFRA
          type:
            value: KUBERNETES_NAMESPACE
          identifier:
            fragments:
              - attribute: k8s.cluster.name
              - value: ":"
              - attribute: k8s.namespace.name
            hashAlgorithm: FARM_HASH
      target:  
        extractGuid:
          attribute: entity.guid
          entityType:
            value: KUBERNETES_DEPLOYMENT