relationships:
  - name: apmApplicationCallsOracleDbFromMetrics
    version: "1"
    origins:
      - Distributed Tracing
    conditions:
      - attribute: newrelic.source
        anyOf: ["api.traces.otlp"]
      - attribute: db.system
        anyOf: ["oracle"]
      - attribute: server.address
        present: true
      - attribute: server.port
        present: true
    relationship:
      expires: PT75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: ORACLEDBINSTANCE
          fields:
            - field: hostAddress
              attribute: server.address
            - field: hostPort
              attribute: server.port
