relationships:
  - name: otelApplicationCallsOracleDbFromMetrics
    version: "1"
    origins:
      - Distributed Tracing
    conditions:
      - attribute: newrelic.source
        anyOf: ["api.traces.otlp"]
      - attribute: db.system
        anyOf: ["oracle"]
      - attribute: server.address
        present: true
      - attribute: server.port
        present: true
    relationship:
      expires: PT75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: ORACLEDBINSTANCE
          fields:
            - field: hostAddress
              attribute: server.address
            - field: hostPort
              attribute: server.port
  - name: nativeapmApplicationCallsOtelOracleDb
    version: "1"
    origins: 
      - APM Metrics
    conditions:
      - attribute: metricName
        anyOf: ["apm.service.datastore.operation.duration"]
      - attribute: peer.hostname
        present: true

    relationship:
      expires: PT75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: ORACLEDBINSTANCE_HOSTONLY
          fields:
            - field: hostAddress
              attribute: peer.hostname
  - name: nrdotInfraCallsOtelOracleDb
    version: "1"
    origins:
      - OnHost Integration
    conditions:
      - attribute: entity.type
        anyOf: ["HOST"]
      - attribute: host.name
        present: true
    relationship:
      expires: PT75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: ORACLEDBINSTANCE_HOSTONLY
          fields:
            - field: hostAddress
              attribute: host.name