domain: INFRA
type: AWSPROMETHEUSWORKSPACE
configuration:
  entityExpirationTime: DAILY
  alertable: true
goldenTags:
- aws.accountId

ownership:
  primaryOwner:
    teamName: "Cloud Monitoring Platform"
