name: validate entity synthesis definitions
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    name: Validation
    runs-on: ubuntu-latest
    env:
      # Path to use for definitions location
      DEFINITIONS_PATH: '../prcode'

      # Used on scripts to validate specific definitions
      RELATIONSHIPS_SYNTHESIS_DIR: ../prcode/relationships/synthesis/
      DEFINITIONS_DIR: ../prcode/entity-types/
    steps:
      # Checkout base branch for validation scripts
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          persist-credentials: false

      # Checkout PR code in unprivileged context
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: "prcode"
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm --prefix validator install

      - name: Validate definition
        run: npm --prefix validator run check

      - name: Ensure sanitize was run
        # Runs the sanitize script and checks errors if the dashboards were not sanitized.
        # If the dashboards were sanitized, the git command will return 0 and the step will pass.
        run: npm --prefix validator run sanitize-dashboards &&  git -C prcode diff-index --quiet HEAD -- entity-types/
